// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("rescript/lib/js/string.js");
var Belt_List = require("rescript/lib/js/belt_List.js");

function toString(t) {
  switch (t.TAG | 0) {
    case /* Var */0 :
        return t._0;
    case /* App */1 :
        return "(" + toString(t._0) + toString(t._1) + ")";
    case /* Fun */2 :
        return "(λ" + t._0 + "." + toString(t._1) + ")";
    
  }
}

function equal(_s, _t) {
  while(true) {
    var t = _t;
    var s = _s;
    switch (s.TAG | 0) {
      case /* Var */0 :
          switch (t.TAG | 0) {
            case /* Var */0 :
                return s._0 === t._0;
            case /* App */1 :
            case /* Fun */2 :
                return false;
            
          }
      case /* App */1 :
          switch (t.TAG | 0) {
            case /* App */1 :
                if (!equal(s._0, t._0)) {
                  return false;
                }
                _t = t._1;
                _s = s._1;
                continue ;
            case /* Var */0 :
            case /* Fun */2 :
                return false;
            
          }
      case /* Fun */2 :
          switch (t.TAG | 0) {
            case /* Var */0 :
            case /* App */1 :
                return false;
            case /* Fun */2 :
                if (s._0 !== t._0) {
                  return false;
                }
                _t = t._1;
                _s = s._1;
                continue ;
            
          }
      
    }
  };
}

function getFreeVariables(t) {
  switch (t.TAG | 0) {
    case /* Var */0 :
        return {
                hd: t._0,
                tl: /* [] */0
              };
    case /* App */1 :
        return Belt_List.concatMany([
                    getFreeVariables(t._0),
                    getFreeVariables(t._1)
                  ]);
    case /* Fun */2 :
        var f = t._0;
        return Belt_List.keep(getFreeVariables(t._1), (function (x) {
                      return x !== f;
                    }));
    
  }
}

var nameOrder = {
  contents: 0
};

function getNewname(param) {
  nameOrder.contents = nameOrder.contents + 1 | 0;
  return "@" + nameOrder.contents.toString();
}

function subst(x, va, body) {
  switch (body.TAG | 0) {
    case /* Var */0 :
        if (body._0 === x) {
          return va;
        } else {
          return body;
        }
    case /* App */1 :
        return {
                TAG: /* App */1,
                _0: subst(x, va, body._0),
                _1: subst(x, va, body._1)
              };
    case /* Fun */2 :
        var arg = body._1;
        var f = body._0;
        if (!Belt_List.has(getFreeVariables(va), f, $$String.equal)) {
          if (f === x) {
            return body;
          } else {
            return {
                    TAG: /* Fun */2,
                    _0: f,
                    _1: subst(x, va, arg)
                  };
          }
        }
        var newSym = getNewname(undefined);
        var newArg = subst(f, {
              TAG: /* Var */0,
              _0: newSym
            }, arg);
        if (f === x) {
          return {
                  TAG: /* Fun */2,
                  _0: newSym,
                  _1: subst(newSym, va, newArg)
                };
        } else {
          return {
                  TAG: /* Fun */2,
                  _0: newSym,
                  _1: subst(x, va, newArg)
                };
        }
    
  }
}

function $$eval(_t) {
  while(true) {
    var t = _t;
    switch (t.TAG | 0) {
      case /* Var */0 :
          return t;
      case /* App */1 :
          var arg = t._1;
          var k = $$eval(t._0);
          switch (k.TAG | 0) {
            case /* Var */0 :
            case /* App */1 :
                return {
                        TAG: /* App */1,
                        _0: k,
                        _1: $$eval(arg)
                      };
            case /* Fun */2 :
                var va = $$eval(arg);
                _t = subst(k._0, va, k._1);
                continue ;
            
          }
      case /* Fun */2 :
          return {
                  TAG: /* Fun */2,
                  _0: t._0,
                  _1: $$eval(t._1)
                };
      
    }
  };
}

function evalOneStep(t) {
  switch (t.TAG | 0) {
    case /* Var */0 :
        return t;
    case /* App */1 :
        var arg = t._1;
        var x = evalOneStep(t._0);
        switch (x.TAG | 0) {
          case /* Var */0 :
              return {
                      TAG: /* App */1,
                      _0: {
                        TAG: /* Var */0,
                        _0: x._0
                      },
                      _1: evalOneStep(arg)
                    };
          case /* App */1 :
              return {
                      TAG: /* App */1,
                      _0: {
                        TAG: /* App */1,
                        _0: x._0,
                        _1: x._1
                      },
                      _1: arg
                    };
          case /* Fun */2 :
              var va = evalOneStep(arg);
              return subst(x._0, va, x._1);
          
        }
    case /* Fun */2 :
        return {
                TAG: /* Fun */2,
                _0: t._0,
                _1: evalOneStep(t._1)
              };
    
  }
}

function evalToFixedPoint(_t) {
  while(true) {
    var t = _t;
    var prevStr = toString(t);
    var succStr = toString(evalOneStep(t));
    console.log("Prev: " + prevStr + " ; Succ: " + succStr);
    if (prevStr === succStr) {
      console.log("Reached fixed point: " + succStr);
      return t;
    }
    _t = evalOneStep(t);
    continue ;
  };
}

function evalOneStepMem(t, cache) {
  var a = Belt_List.getAssoc(cache, toString(t), $$String.equal);
  if (a !== undefined) {
    console.log("Found recursive pattern: " + toString(t) + " which evaluates to: " + toString(a));
    return [
            a,
            cache
          ];
  }
  switch (t.TAG | 0) {
    case /* Var */0 :
        return [
                t,
                Belt_List.setAssoc(cache, toString(t), t, $$String.equal)
              ];
    case /* App */1 :
        var arg = t._1;
        var match = evalOneStepMem(t._0, cache);
        var x = match[0];
        switch (x.TAG | 0) {
          case /* Var */0 :
              var match$1 = evalOneStepMem(arg, match[1]);
              return [
                      {
                        TAG: /* App */1,
                        _0: {
                          TAG: /* Var */0,
                          _0: x._0
                        },
                        _1: match$1[0]
                      },
                      Belt_List.setAssoc(match$1[1], toString(t), t, $$String.equal)
                    ];
          case /* App */1 :
              var match$2 = evalOneStepMem(arg, match[1]);
              return [
                      {
                        TAG: /* App */1,
                        _0: {
                          TAG: /* App */1,
                          _0: x._0,
                          _1: x._1
                        },
                        _1: match$2[0]
                      },
                      Belt_List.setAssoc(match$2[1], toString(t), t, $$String.equal)
                    ];
          case /* Fun */2 :
              var match$3 = evalOneStepMem(arg, match[1]);
              return [
                      subst(x._0, match$3[0], x._1),
                      Belt_List.setAssoc(match$3[1], toString(t), t, $$String.equal)
                    ];
          
        }
    case /* Fun */2 :
        var match$4 = evalOneStepMem(t._1, cache);
        return [
                {
                  TAG: /* Fun */2,
                  _0: t._0,
                  _1: match$4[0]
                },
                Belt_List.setAssoc(match$4[1], toString(t), t, $$String.equal)
              ];
    
  }
}

function evalToFixedPointMem(t) {
  var _t = t;
  var _cache = /* [] */0;
  while(true) {
    var cache = _cache;
    var t$1 = _t;
    var prevStr = toString(t$1);
    var match = evalOneStepMem(t$1, cache);
    var tNext = match[0];
    var succStr = toString(tNext);
    console.log("Prev: " + prevStr + " ; Succ: " + succStr);
    if (prevStr === succStr) {
      console.log("Reached fixed point: " + succStr);
      return t$1;
    }
    _cache = Belt_List.setAssoc(match[1], prevStr, t, $$String.equal);
    _t = tNext;
    continue ;
  };
}

var Lambda = {
  toString: toString,
  equal: equal,
  getFreeVariables: getFreeVariables,
  nameOrder: nameOrder,
  getNewname: getNewname,
  subst: subst,
  $$eval: $$eval,
  evalOneStep: evalOneStep,
  evalToFixedPoint: evalToFixedPoint,
  evalOneStepMem: evalOneStepMem,
  evalToFixedPointMem: evalToFixedPointMem
};

var input = {
  TAG: /* Fun */2,
  _0: "x",
  _1: {
    TAG: /* Var */0,
    _0: "x"
  }
};

console.log(toString(input));

var output = evalToFixedPointMem(input);

console.log(toString(output));

var smallOmega = {
  TAG: /* Fun */2,
  _0: "x",
  _1: {
    TAG: /* App */1,
    _0: {
      TAG: /* Var */0,
      _0: "x"
    },
    _1: {
      TAG: /* Var */0,
      _0: "x"
    }
  }
};

var omega = {
  TAG: /* App */1,
  _0: smallOmega,
  _1: smallOmega
};

console.log(toString(omega));

console.log(toString(evalToFixedPointMem(omega)));

var ycomb = {
  TAG: /* Fun */2,
  _0: "f",
  _1: {
    TAG: /* App */1,
    _0: {
      TAG: /* Fun */2,
      _0: "x",
      _1: {
        TAG: /* App */1,
        _0: {
          TAG: /* Var */0,
          _0: "f"
        },
        _1: {
          TAG: /* App */1,
          _0: {
            TAG: /* Var */0,
            _0: "x"
          },
          _1: {
            TAG: /* Var */0,
            _0: "x"
          }
        }
      }
    },
    _1: {
      TAG: /* Fun */2,
      _0: "x",
      _1: {
        TAG: /* App */1,
        _0: {
          TAG: /* Var */0,
          _0: "f"
        },
        _1: {
          TAG: /* App */1,
          _0: {
            TAG: /* Var */0,
            _0: "x"
          },
          _1: {
            TAG: /* Var */0,
            _0: "x"
          }
        }
      }
    }
  }
};

console.log(toString(ycomb));

console.log(toString(evalToFixedPointMem({
              TAG: /* App */1,
              _0: ycomb,
              _1: {
                TAG: /* Var */0,
                _0: "F"
              }
            })));

var succ = {
  TAG: /* Fun */2,
  _0: "n",
  _1: {
    TAG: /* Fun */2,
    _0: "f",
    _1: {
      TAG: /* Fun */2,
      _0: "x",
      _1: {
        TAG: /* App */1,
        _0: {
          TAG: /* Var */0,
          _0: "f"
        },
        _1: {
          TAG: /* App */1,
          _0: {
            TAG: /* App */1,
            _0: {
              TAG: /* Var */0,
              _0: "n"
            },
            _1: {
              TAG: /* Var */0,
              _0: "f"
            }
          },
          _1: {
            TAG: /* Var */0,
            _0: "x"
          }
        }
      }
    }
  }
};

var zero = {
  TAG: /* Fun */2,
  _0: "f",
  _1: {
    TAG: /* Fun */2,
    _0: "x",
    _1: {
      TAG: /* Var */0,
      _0: "x"
    }
  }
};

function toChurchNum(n) {
  var _n = n;
  var _churchNum = zero;
  while(true) {
    var churchNum = _churchNum;
    var n$1 = _n;
    if (n$1 < 0) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "Demo.res",
              219,
              14
            ],
            Error: new Error()
          };
    }
    if (n$1 === 0) {
      return churchNum;
    }
    _churchNum = {
      TAG: /* App */1,
      _0: succ,
      _1: churchNum
    };
    _n = n$1 - 1 | 0;
    continue ;
  };
}

var numbers_0 = toChurchNum(0);

var numbers_1 = {
  hd: toChurchNum(1),
  tl: /* [] */0
};

var numbers = {
  hd: numbers_0,
  tl: numbers_1
};

var if_then_else = {
  TAG: /* Fun */2,
  _0: "t",
  _1: {
    TAG: /* Fun */2,
    _0: "x",
    _1: {
      TAG: /* Fun */2,
      _0: "y",
      _1: {
        TAG: /* App */1,
        _0: {
          TAG: /* App */1,
          _0: {
            TAG: /* Var */0,
            _0: "t"
          },
          _1: {
            TAG: /* Var */0,
            _0: "x"
          }
        },
        _1: {
          TAG: /* Var */0,
          _0: "y"
        }
      }
    }
  }
};

var trueC = {
  TAG: /* Fun */2,
  _0: "x",
  _1: {
    TAG: /* Fun */2,
    _0: "y",
    _1: {
      TAG: /* Var */0,
      _0: "x"
    }
  }
};

var falseC = {
  TAG: /* Fun */2,
  _0: "x",
  _1: {
    TAG: /* Fun */2,
    _0: "y",
    _1: {
      TAG: /* Var */0,
      _0: "y"
    }
  }
};

var add = {
  TAG: /* Fun */2,
  _0: "n",
  _1: {
    TAG: /* Fun */2,
    _0: "m",
    _1: {
      TAG: /* Fun */2,
      _0: "f",
      _1: {
        TAG: /* Fun */2,
        _0: "x",
        _1: {
          TAG: /* App */1,
          _0: {
            TAG: /* App */1,
            _0: {
              TAG: /* Var */0,
              _0: "n"
            },
            _1: {
              TAG: /* Var */0,
              _0: "f"
            }
          },
          _1: {
            TAG: /* App */1,
            _0: {
              TAG: /* App */1,
              _0: {
                TAG: /* Var */0,
                _0: "m"
              },
              _1: {
                TAG: /* Var */0,
                _0: "f"
              }
            },
            _1: {
              TAG: /* Var */0,
              _0: "x"
            }
          }
        }
      }
    }
  }
};

var iszero_1 = {
  TAG: /* App */1,
  _0: {
    TAG: /* App */1,
    _0: {
      TAG: /* Var */0,
      _0: "n"
    },
    _1: {
      TAG: /* Fun */2,
      _0: "z",
      _1: falseC
    }
  },
  _1: trueC
};

var iszero = {
  TAG: /* Fun */2,
  _0: "n",
  _1: iszero_1
};

var pair = {
  TAG: /* Fun */2,
  _0: "x",
  _1: {
    TAG: /* Fun */2,
    _0: "y",
    _1: {
      TAG: /* Fun */2,
      _0: "z",
      _1: {
        TAG: /* App */1,
        _0: {
          TAG: /* App */1,
          _0: {
            TAG: /* Var */0,
            _0: "z"
          },
          _1: {
            TAG: /* Var */0,
            _0: "x"
          }
        },
        _1: {
          TAG: /* Var */0,
          _0: "y"
        }
      }
    }
  }
};

var fst_1 = {
  TAG: /* App */1,
  _0: {
    TAG: /* Var */0,
    _0: "p"
  },
  _1: trueC
};

var fst = {
  TAG: /* Fun */2,
  _0: "p",
  _1: fst_1
};

var snd_1 = {
  TAG: /* App */1,
  _0: {
    TAG: /* Var */0,
    _0: "p"
  },
  _1: falseC
};

var snd = {
  TAG: /* Fun */2,
  _0: "p",
  _1: snd_1
};

var pred_1 = {
  TAG: /* App */1,
  _0: fst,
  _1: {
    TAG: /* App */1,
    _0: {
      TAG: /* App */1,
      _0: {
        TAG: /* Var */0,
        _0: "n"
      },
      _1: {
        TAG: /* Fun */2,
        _0: "p",
        _1: {
          TAG: /* App */1,
          _0: {
            TAG: /* App */1,
            _0: pair,
            _1: {
              TAG: /* App */1,
              _0: snd,
              _1: {
                TAG: /* Var */0,
                _0: "p"
              }
            }
          },
          _1: {
            TAG: /* App */1,
            _0: succ,
            _1: {
              TAG: /* App */1,
              _0: snd,
              _1: {
                TAG: /* Var */0,
                _0: "p"
              }
            }
          }
        }
      }
    },
    _1: {
      TAG: /* App */1,
      _0: {
        TAG: /* App */1,
        _0: pair,
        _1: zero
      },
      _1: zero
    }
  }
};

var pred = {
  TAG: /* Fun */2,
  _0: "n",
  _1: pred_1
};

var f_1 = {
  TAG: /* Fun */2,
  _0: "n",
  _1: {
    TAG: /* Fun */2,
    _0: "m",
    _1: {
      TAG: /* App */1,
      _0: {
        TAG: /* App */1,
        _0: {
          TAG: /* App */1,
          _0: if_then_else,
          _1: {
            TAG: /* App */1,
            _0: iszero,
            _1: {
              TAG: /* Var */0,
              _0: "n"
            }
          }
        },
        _1: zero
      },
      _1: {
        TAG: /* App */1,
        _0: {
          TAG: /* App */1,
          _0: add,
          _1: {
            TAG: /* Var */0,
            _0: "m"
          }
        },
        _1: {
          TAG: /* App */1,
          _0: {
            TAG: /* App */1,
            _0: {
              TAG: /* Var */0,
              _0: "f"
            },
            _1: {
              TAG: /* App */1,
              _0: pred,
              _1: {
                TAG: /* Var */0,
                _0: "n"
              }
            }
          },
          _1: {
            TAG: /* Var */0,
            _0: "m"
          }
        }
      }
    }
  }
};

var f = {
  TAG: /* Fun */2,
  _0: "f",
  _1: f_1
};

var mulR_0 = {
  TAG: /* Fun */2,
  _0: "Y",
  _1: {
    TAG: /* App */1,
    _0: {
      TAG: /* Var */0,
      _0: "Y"
    },
    _1: f
  }
};

var mulR = {
  TAG: /* App */1,
  _0: mulR_0,
  _1: ycomb
};

var mul2by2_0 = {
  TAG: /* App */1,
  _0: mulR,
  _1: toChurchNum(2)
};

var mul2by2_1 = toChurchNum(2);

var mul2by2 = {
  TAG: /* App */1,
  _0: mul2by2_0,
  _1: mul2by2_1
};

console.log(toString($$eval(mul2by2)));

var one = {
  TAG: /* Fun */2,
  _0: "f",
  _1: {
    TAG: /* Fun */2,
    _0: "x",
    _1: {
      TAG: /* App */1,
      _0: {
        TAG: /* Var */0,
        _0: "f"
      },
      _1: {
        TAG: /* Var */0,
        _0: "x"
      }
    }
  }
};

var mul = {
  TAG: /* Fun */2,
  _0: "n",
  _1: {
    TAG: /* Fun */2,
    _0: "m",
    _1: {
      TAG: /* App */1,
      _0: {
        TAG: /* Var */0,
        _0: "m"
      },
      _1: {
        TAG: /* Var */0,
        _0: "n"
      }
    }
  }
};

var bug = {
  TAG: /* Fun */2,
  _0: "x",
  _1: {
    TAG: /* Fun */2,
    _0: "y",
    _1: {
      TAG: /* App */1,
      _0: {
        TAG: /* App */1,
        _0: {
          TAG: /* Var */0,
          _0: "x"
        },
        _1: {
          TAG: /* Var */0,
          _0: "y"
        }
      },
      _1: {
        TAG: /* App */1,
        _0: {
          TAG: /* Fun */2,
          _0: "x",
          _1: {
            TAG: /* Var */0,
            _0: "x"
          }
        },
        _1: {
          TAG: /* Var */0,
          _0: "x"
        }
      }
    }
  }
};

exports.Lambda = Lambda;
exports.input = input;
exports.output = output;
exports.omega = omega;
exports.ycomb = ycomb;
exports.succ = succ;
exports.zero = zero;
exports.one = one;
exports.toChurchNum = toChurchNum;
exports.numbers = numbers;
exports.mul = mul;
exports.if_then_else = if_then_else;
exports.trueC = trueC;
exports.falseC = falseC;
exports.add = add;
exports.iszero = iszero;
exports.pair = pair;
exports.fst = fst;
exports.snd = snd;
exports.pred = pred;
exports.mulR = mulR;
exports.mul2by2 = mul2by2;
exports.bug = bug;
/*  Not a pure module */
